#@ load("@ytt:data", "data")
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: #@ data.values.workloads.name
  namespace: #@ data.values.workloads.namespace
spec:
  classRef:
    name: #@ data.values.classclaim.name
  parameters:
    workloadRef:
      name: #@ data.values.workloads.name
    redirectPaths:
      - #@ "/login/oauth2/code/{}".format(data.values.workloads.name)
    displayName: "AppSSO Starter Java"
    authorizationGrantTypes:
      - authorization_code
    scopes:
      - name: openid
      - name: profile
      - name: email
    clientAuthenticationMethod: client_secret_basic
    requireUserConsent: true
