#@ load("@ytt:data", "data")
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: testcontainers-pipeline
  namespace: #@ data.values.workloads.namespace
  labels:
    apps.tanzu.vmware.com/pipeline: testcontainers-pipeline
spec:
  params:
    - name: source-url
    - name: source-revision
    - name: docker-secret-name
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
        - name: docker-secret-name
          value: $(params.docker-secret-name)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
          - name: docker-secret-name
        stepTemplate:
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: "RuntimeDefault"
            runAsNonRoot: true
        volumes:
          - name: docker-cert-path
            secret:
              secretName: $(params.docker-secret-name)
        steps:
          - name: test
            image: gradle
            script: |-
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m
              ./gradlew test --info
            env:
            - name: DOCKER_HOST
              valueFrom:
                secretKeyRef:
                  key: docker_host
                  name: $(params.docker-secret-name)
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: DOCKER_CERT_PATH
              value: "/var/docker/certs"
            volumeMounts:
              - name: docker-cert-path
                mountPath: "/var/docker/certs"
